name: hashing-experiments
channels:
    - conda-forge
dependencies:
    - python
    - jupyter
    - ipython
    - pip
    - pip:
      - deap
      - numpy
      - matplotlib
      - seaborn
      - scikit-learn
      - scipy
      - lshashpy3
      - pmlb
      - joblib
      - statannotations
      - pandas==2.0
      - networkx
      - sympy
      - statsmodels
      - cachetools
