name: hashing-experiments
channels:
    - conda-forge
dependencies:
    - python=3.12.1
    - jupyter
    - ipython
    - pip
    - pip:
      - deap
      - numpy
      - matplotlib
      - seaborn
      - scikit-learn
      - scipy
      - lshashpy3
      - pmlb
      - joblib
      - statannotations
      - pandas
